browse_categories:
- Compute
- Containers
code: https://aws.amazon.com/ecs/
data_signature: namespace:"AWS/ECS"
description: Integrate SignalFx with Amazon EC2 Container Service (ECS)
display_name: Amazon ECS
product_docs_name: amazon.ecs
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awsecs.png
logo_small: integration_awsecs.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-ecs
useLegacyBuild: false
